package com.e444er.ai_dall_e.data.model

class GeneratedImageError {
}